// <auto-generated />
namespace NewMotivationHR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AFTER_ALTER_TABLE_SALARY : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AFTER_ALTER_TABLE_SALARY));
        
        string IMigrationMetadata.Id
        {
            get { return "202203060757444_AFTER_ALTER_TABLE_SALARY"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
