// <auto-generated />
namespace NewMotivationHR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_employee_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_employee_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "202202171535160_add_employee_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
