// <auto-generated />
namespace NewMotivationHR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update3colum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update3colum));
        
        string IMigrationMetadata.Id
        {
            get { return "202203251533005_update3colum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
